Feature/bag submit data cucumber
flow-build/blueprint-builder-template pull request #4
Opened 2022-04-07 17:44 UTC by pedropereiraassis

Adição da dependência do mustache;
Alteração da BP de testes para abranger o novo step do cucumber;
Adição da função wait no arquivo de steps (para não ficar no método getProcessHistory e evitar possíveis erros);
Alteração do arquivo de testes da BP de teste;
Alteração do step 'submitActivity' para simular o submite de valor da bag quando há valores entre duas chaves no payload;
OBS: não achei necessário adicionar um step que verifica se "guarda" o valor na bag, pois é possível buscar diretamente da bag do histórico do processo, e se o valor não é guardado o teste vai no END-ERROR. Mas se achar necessário posso adicionar esse step.
OBS 2: Tive de incluir dois métodos de Object (guardando os pares key/value em um array e retornando novamente para um objeto com todos valores em string) pois o método mustache.render() puxa o valor do objeto como um número e dá erro no submit (que normalmente espera string).

2022-04-10 13:52 UTC, gustavo-fdte requested changes

2022-04-10 13:52 UTC, gustavo-fdte commented on tests/features/support/steps.js
>  Then("the process passes through {string}", { timeout: 60 * 1000 }, async function (node) {
O termo correto seria no passado. _The process passed through node {string}_.

2022-04-10 13:52 UTC, gustavo-fdte commented on tests/features/support/steps.js
> +  await wait(500);
Acho que para a solução ficar mais resiliente, ao invés de colocar um wait você poderia verificar se o processo parou.

2022-04-10 13:52 UTC, gustavo-fdte commented on tests/features/support/world.js
> +      const nodeState = this.history.find(state => state.status === "waiting");
Os dados submetidos na userTask não devem ser dados extraídos diretamente da bag.
Eles podem ser derivados da bag, mas isso deve ser primeiro extraído da bag, armazenado em outro espaço, permitir que o usuário manipule esse dado e, em seguida retorne para para o processo no submit.
Primeiro precisamos criar um contexto de teste (ou de cenário) em que o usuário pode guardar dados.
Deve existir um step que permite o usuário manipular esse contexto de dados, manualmente ou a partir de dados do processo.
Aí sim entra um step em que o usuário pode montar um payload dinâmico a partir dos dados do contexto do cenário.

2022-04-11 15:17 UTC, pedropereiraassis commented on tests/features/support/world.js
> +      const nodeState = this.history.find(state => state.status === "waiting");
Alteração realizada: o valor submetido agora busca da nova variável do arquivo world : worldData.

2022-04-12 21:44 UTC, gharamura commented on tests/features/support/world.js
> +let worldData = {};
E se, ao invés de salvar o worldData em memória, worldData fosse um arquivo na pasta que vc altera?
Isso permitiria vc passar dados de um processo para outro.
Exemplo: vc inicia o processo de login e obtém o token, salva no worldData para poder usar no próximo processo.

2022-04-12 23:09 UTC, pedropereiraassis commented on tests/features/support/world.js
> +let worldData = {};
Alteração realizada. As variáveis ficam salvas no arquivo 'worldData.json' para posterior utilização.

2022-04-22 15:32 UTC, gharamura approved these changes

2022-04-25 12:35 UTC, merged